const images = [
    "aurora-borealis_banner.png",
    "baked-model-viewer-preview.png",
    "baked-model-viewer.png",
    "bioma-preview.png",
    "data-sculpture-banner.png",
    "drifting-banner.png",
    "esquejes-preview.png",
    "ether-crib-banner.png",
    "ferlat-biorremediaciones-1.png",
    "ferlat-biorremediaciones-2.png",
    "flag-argentina.png",
    "flag-united-kingdom.png",
    "flag-united-states.png",
    "foliage-preview.png",
    "gray-matter-banner.png",
    "kinectic-sculpture-banner.png",
    "lockdown-banner.png",
    "meta-banner.png",
    "momentum-banner.png",
    "no-existe-tierra-mas-alla.jpg",
    "observaciones-sobre-el-ruido-en la-condensación-de-una-nube-banner.png",
    "paranoia-banner.png",
    "pedro-falco-img-crop.png",
    "pedro-falco-img.png",
    "persistence-reality-banner.png",
    "pixel-bloom-banner.png",
    "promised-hesitate-banner.png",
    "rafagas-registro-1.png",
    "rhizome_banner.png",
    "srchers-preview.png",
    "tkdevolution-preview.png",
    "esquejes/esquejes-1.png",
    "esquejes/esquejes-10.png",
    "esquejes/esquejes-11.png",
    "esquejes/esquejes-2.png",
    "esquejes/esquejes-3.png",
    "esquejes/esquejes-4.png",
    "esquejes/esquejes-5.png",
    "esquejes/esquejes-6.png",
    "esquejes/esquejes-7.png",
    "esquejes/esquejes-8.png",
    "esquejes/esquejes-9.png",
    "esquejes/esquejes-bm-1.jpg",
    "esquejes/esquejes-bm-2.jpg",
    "esquejes/esquejes-bm-3.jpg",
    "esquejes/esquejes-bm-4.jpg",
    "esquejes/esquejes-bm-5.jpg",
    "foliage/color/angle-100000145.png",
    "foliage/color/grid-100000016.png",
    "foliage/color/random-100000097.png",
    "foliage/intro/1200px-VectorField.svg.png",
    "foliage/intro/dataviz.png",
    "foliage/palette/Alisio-100000110.png",
    "foliage/palette/anime.png",
    "foliage/palette/Bise-100000032.png",
    "foliage/palette/Bora-100000156.png",
    "foliage/palette/Cordonazo-100000142.png",
    "foliage/palette/Gregal-100000077.png",
    "foliage/palette/Kóshkil-100000066.png",
    "foliage/palette/Lebeche-100000018.png",
    "foliage/palette/Levante-100000118.png",
    "foliage/palette/Minuano-100000152.png",
    "foliage/palette/Mistral-100000116.png",
    "foliage/palette/Monzon-100000130.png",
    "foliage/palette/Ostro-100000144.png",
    "foliage/palette/Pampero-100000168.png",
    "foliage/palette/Passat-100000146.png",
    "foliage/palette/Poniente-100000005.png",
    "foliage/palette/Puelche-100000046.png",
    "foliage/palette/Rashabar-100000189.png",
    "foliage/palette/Sirocco-100000128.png",
    "foliage/palette/Sudestada-100000138.png",
    "foliage/palette/Tramontana-100000109.png",
    "foliage/palette/Zonda-100000002.png",
    "foliage/pollen/hard-100000029.png",
    "foliage/pollen/light-100000153.png",
    "foliage/pollen/off-100000167.png",
    "foliage/style/anime.png",
    "foliage/style/clean-100000162.png",
    "foliage/style/magic-100000120.png",
    "foliage/style/shady-100000019.png",
    "foliage/style/veins-100000054.png",
    "foliage/surface-analisys/A vegetation near a river course-100000193.png",
    "foliage/surface-analisys/Forgotten leaves on a hill-100000195.png",
    "foliage/surface-analisys/My mom's yard-100000176.png",
    "foliage/surface-analisys/my neighbors vineyard 100000196.png",
    "foliage/surface-analisys/Petals on my grandpa's desk-100000080.png",
    "foliage/surface-analisys/Some plants a few blocks from a house-100000192.png",
    "foliage/surface-analisys/Spikes from a infected plant-100000186.png",
    "foliage/surface-analisys/The lawn of a noble garden-100000134.png",
    "foliage/surface-analisys/the weeds of an abandoned land-100000159.png",
]

const videos = [
    "artdao-colors.mp4",
    "artdao-overview.mp4",
    "artdao-preview.mp4",
    "asterisms-preview.mp4",
    "asterisms-trailer.mp4",
    "boost-trailer.mp4",
    "bioma.mp4",
    "entre-la-basura-ur-preview.mp4",
    "expulso-teaser.mp4",
    "ferlat-biorremediaciones.mp4",
    "la-nube-registro.mp4",
    "rafagas registro.mp4",
    "rafagas_registro.mp4",
    "tkdevolution.mp4",
    "srchers.mp4",
];

export { images, videos };