export default {
    en: {
        proyectos: "Works",
        bio: "About",
        gen_art: "Generative Art",
        inst: "Installation",
        web_app: "Web Application",
        vr: "Virtual Reality",
        work: "Work:",
        proj_description: "Designs that merge research, programming, art and data.",
        about_description: "Designer, Artist and Educator. I write images with computers.",
        project_complete: "Complete project:",
        contract_address: "Contract address:",
        bio_0:
            "Pedro Falco (b. 1997) is a generative artist and designer based in Buenos Aires, Argentina, who writes images with computers. His work explores generative systems, databases, procedural modeling and blockchain technology to create images, interactive installations, online experiences and electronic objects.",
        bio_1:
            "Through a curious and obsessive approach, his work is a way he found to continue researching and learning in what he likes to call «the identity of the pixel». His work has been exhibited in Buenos Aires, Bogota and Rio de Janeiro and he has held numerous workshops at the Centro Cultural de España en Buenos Aires, Bafici, Centro Cultural Recoleta and TRImarchi, among others.",
        bio_2:
            'Pedro Falco is a professor at the University of Buenos Aires, Argentina, where he holds a degree in Image and Sound Design.',
        contact: "Feel free to write me for any question :)",
        asterisms_0:
            "An asterism is a collection of stars that, when one connects them mentally, they generate a pattern. Unlike constellations, they are a more general concept that can refer to any identified pattern of stars. The viewer is the one who draws in the sky and gives meaning to their creation.",
        asterisms_1:
            "'Asterisms' in an interactive generative project that invites you to draw, name and save forever your own asterism. Through a generative algorithm, the script gives you the sky as a canvas where you can unfold your imagination as many times as you want based on the Token ID hash from the minting process.",
        asterisms_2: "To be a user is to be a creator.",
        asterisms_3:
            "Instructions: LEFT CLICK to create stars │ Use the MOUSE WHEEL to zoom in and out │ TYPE to write a title │ BACKSPACE to delete text │ DELETE to delete all the text │ ENTER to save the file.",
        asterisms_4:
            "The project was launched on April 20, 2021 on the ArtBlocks platform, being one of the earliest projects to take advantage of blockchain technology and web programming to generate interactive experiences in real time.",
        asterisms_5:
            "My interest in this project lies precisely in exploring these new possibilities that Blockchain technology and the ArtBlocks platform enabled. At that time, the crypto ecosystem was debating whether the work was the image or the information that the token had. Within that context, it seemed interesting to me to generate a simple work (technically speaking) but that could allow me to talk about this and the problem of using rigid or inflexible categories.",
        asterisms_6:
            "As their name indicates, asterisms are groups of stars grouped together by the viewer and only make sense within their  context.",
        asterisms_7:
            "The project had a great reception by collectors who, after discovering how the interactivity worked, highlighted the poetics generated by the algorithm. Today the project consists of 100 iterations stored immutably on the Ethereum blockchain.",
        foliage_0:
            '"Foliage" is a moment of pause. The project was born from the futile attempt to catch a breath of wind, the one that no one sees but everyone notices when the leaves hang trembling. Inspired by long days near the Rio de la Plata studying the wind, this series of 250 foliage is an exploration of how angles and colors can generate the illusion of movement and harmony. "Foliage" is inspired on wind data visualizations where the use of angles and vectors speak of a trajectory. Winds, like data, travel through our world leaving a trace; this time hosted immutably on the Ethereum Blockchain.',
        foliage_1:
            'As I said, "Foliage" is inspired by the area where I grew up and lived most of my life. Very close to my house, a few blocks away, is the Río de la Plata, which is a very beautiful place, with lots of wind and vegetation. From that observation is that the project was born. That is why Foliage presents nine different types of plants and the name of each one is inspired by landscapes close to me.',
        foliage_2:
            "The category is called 'surface analysis' because when you study the winds you need to delimit a research area. In my case, these are my surfaces.",
        foliage_3:
            "Regarding the color palettes, I wanted there to be a wide variety of colors that could reflect many different moments of the year and many different moods.  In that variety, I decided to name the different color palettes following the names of the world's best known winds.",
        foliage_4:
            "To paint the foliage, I chose to use three techniques that I called: Random, Angle and Grid. Each uses a different technique that generates a different pattern. All the ways of coloring the foliage are based on the position and angle relationship that each leaf vector has.",
        foliage_5:
            'Each foliage can have different styles. I separated them into five different styles: Shady, Magic, Clean, Veins and Anime. The "Shady" style has more depth through shadow work that creates volume. In "Magic" the color palette is inverted to color the edges of the leaves, which makes it more vibrant and colorful.In the "Veins" style the border of the leaves can be black or white and this disappears as the leaves scale, while in "Clean" there is no border at all, which at times makes the colors lose their borders. The "Anime" style is quite different and alludes to something mystical.',
        foliage_6:
            "Finally, as the wind blows, the foliage may release more or less pollen, depending on their characteristics. There may be a lot or a light amount of pollen, or no pollen at all.",
        expulso_0:
            "The communication skeleton and its various devices are intended to some kind of response.",
        expulso_1: "Where do those words that wish not to be heard go?",
        expulso_2:
            "We live sunk at the bottom of an ocean of air that generates pressure on our bodies. Whoever wants to speak must have the opportunity to speak in a place with less pressure than atmospheric pressure, where the transmission of words in the air does not take place. It is necessary to take the pressure out of what surrounds us. By generating a vacuum, we can generate a decrease of the barometric pressure and thus reduce the real pressure we are talking about.",
        expulso_3:
            "This is why we feel the urgency to destroy the skeleton of communication. To eliminate the idea of sender-medium-receiver. By speaking into the void, we give way to the communication of what we understand as real and which, precisely in the world we live in, is destined to fail.",
        expulso_4:
            "In this way, a decrease in pressure gives rise to the poetics of silent words. A creation born of saying without pressure.",
        expulso_5: "For that, let us enjoy the fertility of emptiness.",
        expulso_6:
            "'EXPULSO' is an interactive installation that consists of a 4mts x 1.20mts x 2.40mts sheet metal room which invites the user to enter to expel. Once inside, the user goes through an airtight curtain and enters the sector where the pressure was decreased. \"What generates pressure for you?\" asks the room and the user must answer through a microphone hanging from the ceiling. While the sound of the words is canceled by the vacuum, the voice transmitted by the microphone causes a generative digital creature modified by the very characteristics of the user's speech to react.",
        expulso_7: "Each creature is unique and child of each person.",
        expulso_8:
            "Designed and produced by Clara Travieso, German Oriana, Abril Portillo, Octavio Castiñeira and Pedro Falco.",
        nube_0:
            "The Cloud is an interactive installation consisting of a small database which listens, stores and executes events that draw the sky as in a performance. The Cloud is an algorithm that seeks to think the behavior of clouds as a generative system.",
        nube_1:
            "However, the installation recalls its playful spirit and, through a graphic interface, invites users to play with the sky and alter the state of the weather while interacting with each other.",
        nube_2:
            "This project is a dialogue between two topics that I have been researching for several years: generative systems and the functioning of the Internet. The Cloud tries to generate a bridge between both universes and put them in dialogue.",
        nube_3:
            "The generation of images in real time is achieved through an algorithm that I developed in TouchDesigner, which listens to events that trigger different states such as the creation of clouds, thunder, rain, comets and data visualization, among others. It also has an internal clock that changes the sky depending on the local time.",
        nube_4:
            "On the other hand, the web interface communicates with TouchDesigner via Socket.IO and sends messages in real time through the Internet generating a fluid and latency-free communication between the users and the system.",
        boost_0:
            "Boost is an audiovisual piece that, through virtual reality, invites you to explore the under universe of car racing in Argentina.",
        boost_1:
            "Combining 360° recordings and 3D animation, the work oscillates between documentary and the sublimation of a state of ecstasy. For a few minutes, the viewer is immersed in a world devoid of pretentiousness, where there is just enough for the driver's condition to be repeated over and over again as the races go by. This eternal return allows the driver, even if only for 13 seconds, to have his moment of glory.",
        boost_2:
            "In this way, what appears to be a straight line with two cars is transformed into something much more complex where adrenaline, passion and senses combine to form a sacred ritual.",
        boost_3:
            'The piece was presented as a site-specific installation at the Avellaneda racetrack in 2018 and also in "La Noche de los Museos" in 2019.',
        boost_4:
            "Designed and realized by Juan Ignacio Migliardo, Abril Portillo, Harry Piluso Mulhall, Octavio Castiñeira and Pedro Falco.",
        meta_0:
            "Beyond what is given. Data about data. An audio spectrum visualization.",
        sr_sale:
            "Digitally generated image and processed in real-time. The work was tokenized on the Ethereum network with SuperRare contracts and is currently for sale.",
        sr_sold:
            "Digitally generated image processed in real-time. The work was tokenized on the Ethereum network with SuperRare contracts and is currently sold.",
        aurora_0:
            "Back wet. One night of solid silence he played his cards and dreams fled hopeless as sand. Ashes, blind equilibrist, getting lost in the air.",
        condensacion_nube_0:
            "Defined by themselves as a generative system, the clouds invite us to think about noise. Noise, like an image, is a moment. It's a challenge to get out of the noise without getting carried away by it. On the one hand, from the balcony, the things to do draw a hole. On the other, the parallels reveal the rational construction of the geoid system while the drops, obsequious, follow the agreed path. In a first approach to the cloud, politically correct considerations emerge: its morphology, digitized in its nature, lends itself to continuous change. At the risk of being wrong, it appears to be nothing more than information flowing camouflaged in red, green and blue containers, a high period and high harmonics. However, a change of state forces the viewer to a change of mood. It is obvious that what is seen always generates something, but the pseudo-randomness of the noise invites speculation as to what generates what it generates. Curled in its same ever-changing path, the observer finds respite in noise. It happens that noise does not seek to be decent. Nor does noise need any arrangement.",
        condensacion_nube_1:
            '"Observaciones sobre el ruido en la condensación de una nube" is a series guided by distress.',
        data_sculpture_0:
            "A data sculpture built from featured tweets mentioning ETH2.0. A document for posterity. Seamless loop 1920 x 1920 px.",
        drifting_0:
            "Drifting from a thought. Autonomous agents driven by rgb values.",
        ether_0:
            "A voyage through ether. The impossible will to taste what we couldn't live.",
        gray_matter_0:
            "Gray Matter is my first generative artwork. It's a continuous flow of data that drifts like a nervous system, leaving a trace, drawing a path. More than a million gray dots, invite us to see secret passages that thought takes to find new connections.",
        kinetic_sculpture_0:
            "Data flows from its skeleton. The construction is revealed. Place the body, place the text. The code as DNA, explains our erratic nature in movement. Live forever.",
        lockdown_0:
            "An attempt to look outward while forcing ourselves to look inward.",
        paranoia_0: "A new twisted journey through the mysteries of thought.",
        persistance_reality_0: "A fatal error during simulation.",
        pixel_bloom_0: "It's for you.-",
        promised_hesitate:
            "Doubt knocks on the door and the entire infinity breaks in.",
        rhizome_0:
            '"Make rhizomes, not roots, never plant! Don’t sow, grow offshoots! Don’t be one or multiple, be multiplicities! Run lines, never plot a point! Speed turns the point into a line! Be quick, even when standing still!"- Gilles Deleuze and Félix Guattari in Capitalism and Schizophrenia (1972–1980)',
        momentum_0: "Every drop of thought,	that you can't think, shake my bones. They slip out of my pockets.",
        basura_0:"'Entre la basura' is a program to see what remains invisible among the spam I receive everyday.",
        basura_1:"The app works by connecting to the Google API to search for mails inside my spam folder. That material is used as a prompt to generate an image with DALL-E. For this, 'Entre la basura' connects to the OpenAi API and generates an image in real time.",
        rafagas_0:"Descripción: Ráfagas es una instalación interactiva que responde al movimiento de las personas que se acercan. Al moverse, lxs usuarixs, ejecutan un algoritmo que devuelve el rastro de esa ráfaga. La imagen resultante, inmóvil, es la creación de interesantes follajes arrastrados por el viento.",
        biorremediaciones_0: "\"Is it possible to balance our relationship with the ecosystem? How can we heal the damage we are doing to the biosphere? These are perhaps the most urgent questions of our time, in which it's evident that the exponential acceleration of the unsustainable model in which we live is reaching an irreversible physical limit as a reflection of a profound crisis of meaning of capitalist society\". Juan Pablo Ferlat.",
        biorremediaciones_1: "Bioremediations series is a research project that links new artificial intelligence technologies and fungi with bioremediation capabilities by degrading pollutants in the environment in which the artist cultivates fungi and records their evolution with different photographic capture techniques",
        biorremediaciones_2: "Four screen video wall. Duration: 6:35\". No sound. Installed at Openhouse by Openbank, Buenos Aires (2022).",	
        biorremediaciones_3: "TouchDesigner development: Pedro Falco. Curator: Cristian Reynaga.",	
        biorremediaciones_4: "Fragment of the video",	
        esquejes_0: "\"Esqueje\" is the Spanish equivalent of cutting or clone. This consists of a fragment of stem cut from a plant and introduced into the ground so that it can take root with the intention of reproducing it, thus generating new clones. \"Esquejes\" is a generative system resulting from algorithmic gardening, which seeks to push the uniqueness of each pixel to the limit. \"Esquejes\" generates interesting shapes and textures using several layers of shaders. In this way, the work seeks to make each pixel different from its neighbor and not lose its individuality in the universe of synthetic images. Because if there are infinite numbers, there are infinite colors.",
        esquejes_1:"Throughout September 2023 Esquejes was generated and exhibited in all Bright Moments galleries (Los Angeles, New York, Berlin, London, Mexico City and Tokyo) as well as on their online platform. In addition, Esquejes was presented at Glitch Marfa Gallery (Marfa, Texas, USA) during October 2023.",
        author: "designed by Pedro Falco @ studio.falko",
        esquejes_2: "The project was done in Javascript and WebGL using the Three.js library. It consists of a deep research on how to generate images with shaders. Specifically this project focuses on one hand on generating an algorithm that generates interesting abstract figures and on the other hand seeks to create textures with folds that pretend three-dimensionality and depth.",
        bioma_0:"BIOMA was an audiovisual proposal made with Agustín Cotroneo for the Electronic Arts Laboratory of Tecnópolis. This installation was exhibited during the months of July and August 2023 and consisted of 12 truss columns with two screen sides each. Each side of 0,50 mts x 4 mts.",
        bioma_1: "The images were designed in TouchDesigner while the sound was generated from video inputs in Ableton Live.", 
        viewer_0:"<a class='underline' target='_blank' href='https://baked-model-viewer.netlify.app/'>baked-model-viewer</a>↗ allows you to explore 3D models with baked textures in GLB format. You can upload your own GLB files containing color, emissive and/or alpha textures, and visualize them in a 3D environment with <a class='underline' target='_blank' href='https://threejs.org/docs/#examples/en/controls/PointerLockControls'>point-locker-controls</a>↗.",
        viewer_1:"The app was made using Three.js, Svelte and Tailwind. It works by including the words \"color\", \"emissive\", and/or \"alpha\" in your image texture filenames.",
        tkd_0:"Tae Kwon Do Evolution is a web application for learning and practicing taekwondo online. The application contains information about different forms of taekwondo accompanied by an interactive 3D model showing the movements.",
        tkd_1:"The application was made using Three.js, Svelte and Tailwind.",
        srchers_0: "I've coded the SRCHERS landing page which consists of a procedural terrain made in Three.js and an interactive camera that responds to mouse coordinates.",
        artdao_0:"I developed the ArtDAO website, an innovative project that incorporates three distinctive color styles. The site integrates Three.js with Svelte to offer an interactive and immersive experience. In addition, it has several sections that capture and faithfully reflect the ethos and essence of the ArtDAO project.",
        cookies:
        "The site was designed keeping your privacy in mind, with no cookies, advertising or requests of any kind. It only caches the images. The website is hosted @ netlify.com and open source @ github.com/pedrofalco",
    },
    es: {
        proyectos: "Proyectos",
        bio: "Bio",
        gen_art: "Arte Generativo",
        inst: "Instalación",
        web_app: "Aplicación Web",
        vr: "Realidad Virtual",
        work: "Obra:",
        proj_description: "Diseños que combinan investigación, programación, arte y datos.",
        about_description: "Diseñador, Artista y Docente. Escribo imágenes con computadoras.",
        project_complete: "Proyecto completo:",
        contract_address: "Dirección del contrato:",
        proj_header: "Projectos.",
        gen_art: "Arte Generativo",
        vr: "Experiencia VR",
        installation: "Instalación",
        web_app: "Aplicación Web",
        bio_0:
            "Pedro Falco (1997) es un artista generativo y diseñador residente en Buenos Aires, Argentina, que escribe imágenes con computadoras. Su trabajo explora los sistemas generativos, las bases de datos, el modelado procedural y la tecnología blockchain para crear imágenes, herramientras open source, experiencias online, instalaciones interactives y objetos electrónicos.",
        bio_1:
            "A través de un enfoque curioso y obsesivo, su trabajo es una forma que encontró para seguir investigando y aprendiendo en lo que le gusta llamar «la identidad del píxel». Su obra ha sido expuesta en Buenos Aires, Bogotá y Río de Janeiro y ha impartido numerosos talleres en el Centro Cultural de España en Buenos Aires, Bafici, Centro Cultural Recoleta y TRImarchi, entre otros.",
        bio_2:
            'Pedro Falco es docente en la Universidad de Buenos Aires, Argentina, donde se recibió en Diseño de Imagen y Sonido.',
        contact: "Escribime por cualquier consulta :)",
        asterisms_0:
            "Un asterismo es un conjunto de estrellas que, cuando uno las conecta mentalmente, estas generan un patrón. A diferencia de las constelaciones, son un concepto más general que puede referirse a cualquier patrón identificado de estrellas. El espectador es quien dibuja en el cielo y da sentido a su creación.",
        asterisms_1:
            "Asterismos en un proyecto generativo interactivo que te invita a dibujar, nombrar y guardar para siempre tu propio asterismo. A través de un algoritmo generativo, el script te ofrece el cielo como un lienzo donde desplegar tu imaginación tantas veces como quieras basándose en el hash del Token ID del proceso de acuñación.",
        asterisms_2: "Ser usuarix es ser artífice.",
        asterisms_3:
            "Instrucciones: CLIC IZQUIERDO para crear estrellas │ Usa la RUEDA para acercar y alejar │ TIPEA para escribir un título │ RETROCESO para borrar │ SUPR para borrar todo el texto │ ENTER para guardar el archivo.",
        asterisms_4:
            "El proyecto fue lanzado el 20 de abril de 2021 en la plataforma ArtBlocks, siendo uno de los primeros proyectos que aprovecharon la tecnologia blockchain y la programacion web para generar experiencias interactivas en tiempo real.",
        asterisms_5:
            "Mi interes por realizar este proyecto radica justamente en explorar esas nuevas posibilidades que la tecnologia Blockchain y la plataforma ArtBlocks habilitaron. En ese momento, el ecosistema crypto se debatia si la obra era la imagen o la informacion que tenia ese token. Dentro de ese contexto, me parecio interesante generar una obra simple en su tecnica pero que permita que este en constante cambio y que permita hablar de la dificultad de utilizar categorias rigidas y cerradas.",
        asterisms_6:
            "Como su nombre lo indica, los asterismos son grupo de estrellas agrupados por quien las mira y solo tienen sentido dentro de la estructura de quien las piensa.",
        asterisms_7:
            "El proyecto tuvo una gran recepción por los coleccionistas quienes luego de descubrir como funcionaba la interactividad, destacaron la poética generada por el algortimo. Hoy en día el proyecto consta de 100 iteraciones almacenadas de manera inmutable en la blockchain de Ethereum.",
        foliage_0:
            '"Foliage" es un momento de pausa. El proyecto nace del vano intento de atrapar un soplo de viento, ese que nadie ve pero que todos notan cuando las hojas cuelgan temblorosas. Inspirada en largas jornadas cerca del Río de la Plata estudiando el viento, esta serie de 250 follajes es una exploración de cómo el trabajo con ángulos y colores pueden generar la ilusión de movimiento y armonía. "Foliage" se inspira en visualizaciones de datos de viento donde el uso de ángulos y vectores hablan de una trayectoria. Los vientos, como los datos, viajan por nuestro mundo dejando un rastro; esta vez alojado de forma inmutable en la Blockchain de Ethereum.',
        foliage_1:
            "Como he mencionado, \"Foliage\" está inspirado en la zona donde crecí y viví gran parte de mi vida. Muy cerca de mi casa, a pocas cuadras, está el Río de la Plata, que es un lugar muy hermoso, con mucho viento y vegetación. De esa observación es que nació el proyecto. Por eso, 'Foliage' presenta nueve tipos diferentes de plantas y el nombre de cada una está inspirado en paisajes cercanos a mí.",
        foliage_2:
            "La categoría se llama análisis de superficie porque en el estudio de los vientos hay que delimitar una zona donde se va a estudiar. En mi caso, estas son mis superficies.",
        foliage_3:
            "En cuanto a las paletas de colores, quería que hubiera una gran variedad de colores que pudieran reflejar muchos momentos diferentes del año y muchos estados de ánimo distintos.  En esa variedad, decidí nombrar las distintas paletas de colores siguiendo los nombres de los vientos más conocidos del mundo.",
        foliage_4:
            "Para pintar el follaje, opté por utilizar tres técnicas que denominé: Aleatorio, Ángulo y Cuadrícula. Cada una utiliza una técnica diferente que genera un patrón distinto. Todas las formas de colorear el follaje se basan en la relación de posición y ángulo que tiene cada vector de hoja.",
        foliage_5:
            'Cada follaje puede tener diferentes estilos. Los he separado en cinco estilos diferentes: Sombreado, Mágico, Limpio, Vetas y Anime. El estilo "Sombreado" tiene más profundidad gracias al trabajo de sombras que crea volumen. En el estilo "Mágico", la paleta de colores se invierte para colorear los bordes de las hojas, lo que lo hace más vibrante y colorido. En el estilo "Venas", el borde de las hojas puede ser blanco o negro y desaparece a medida que las hojas se escalan, mientras que en el "Limpio" no hay ningún borde, lo que a veces hace que los colores pierdan sus bordes. El estilo "Anime" es bastante diferente y alude a algo místico.',
        foliage_6:
            "Por último, al soplar el viento, el follaje puede liberar más o menos polen, en función de sus características. Puede haber mucho o poco polen, o no haber polen en absoluto.",
        expulso_0:
            "El esqueleto de la comunicación y sus distintos dispositivos obligan a que siempre haya alguna respuesta.",
        expulso_1: "¿A donde van aquellas palabras que desean no ser escuchadas?",
        expulso_2:
            "Vivimos sumergidos en el fondo de un océano de aire que genera presión sobre nuestros cuerpos. Quien quiera enunciar debe tener la oportunidad de decir en un lugar con menor presión que la atmosférica, donde la transmisión de las palabras en el aire no se efectúe. Se necesita sacarse la presión de esto que nos rodea. Generando vacío, podemos generar una disminución de la presión barométrica y así llegar a disminuir la presión real de la que hablamos.",
        expulso_3:
            "Es por esto que sentimos la urgencia de destruir el esqueleto de la comunicación. Eliminar la idea de emisor-medio-receptor. Hablándole al vacío, damos lugar a la comunicación de lo que entendemos por real y que justamente en el mundo que vivimos está destinado al fracaso.",
        expulso_4:
            "De esta manera, una disminución de la presión da lugar a la poética de las palabras calladas. Una creación hija de decir sin presión.",
        expulso_5: "Para eso, disfrutemos de la fertilidad del vacío.",
        expulso_6:
            "'EXPULSO' es una instalación interactiva que se compone de una sala de chapa de 4mts x 1.20mts x 2.40mts la cual invita a quien entra a expulsar. Una vez dentro, el usuario o la usuaria atraviesa una cortina hermética e ingresa al sector donde la presión fue disminuida. “¿Qué te genera presión?” pregunta la sala y el ususario debe responder a través de un micrófono que cuelga del techo. Mientras el sonido de las palabras es cancelado por el vacío, la voz transmitida por el micrófono hace reaccionar a una criatura generativa digital modificada por las características mismas del habla del usuario.",
        expulso_7: "Cada criatura es única e hija de cada persona.",
        expulso_8:
            "Diseñado y realizado por Clara Travieso, German Oriana, Abril Portillo, Octavio Castiñeira y Pedro Falco.",
        nube_0:
            "La Nube es una instalación interactiva que consiste en una pequeña base de datos la cual escucha, almacena y ejecuta eventos que dibujan el cielo como en una performance. La Nube es un algoritmo que busca pensar el comportamiento de las nubes como un sistema generativo.",
        nube_1:
            "Sin embargo, la instalación reivindica su el espíritu lúdico y, a través de una interfaz gráfica, invita lxs usuarixs a jugar con el cielo y alterar el estado del clima mientras interactúan entre ellxs.",
        nube_2:
            "Este proyecto en el que dialogan dos tópicos que vengo investigando hace ya varios años que son los sistemas generativos y el funcionamiento de internet. La Nube intenta generar un puente entre ambos universos y ponerlos en diálogo.",
        nube_3:
            "La generación de imágenes en tiempo real está lograda a través de un algoritmo que desarrolle en TouchDesigner, el cual escucha eventos que dispara diferentes estados como la creación de nubes, truenos, lluvia, cometas y visualización de datos, entre otros. Además tiene un reloj interno que hace cambiar el cielo dependiendo la hora local.",
        nube_4:
            "Por otra parte, la interfaz web se comunica con TouchDesigner via Socket.IO y envía los mensajes en tiempo real a través de internet generando una comunicación fluida y sin latencia entre lxs usuarixs y el sistema.",
        boost_0:
            "Boost es una pieza audiovisual que a través de la realidad virtual, invita a explorar el universo under de las picadas de autos en Argentina.",
        boost_1:
            "Combinando grabaciones en 360° y animación 3D, la obra oscila entre el documental y la sublimación de un estado de éxtasis. Durante unos minutos, el espectador se encuentra inmerso en un mundo ausente de pretenciosidad, donde lo que hay es lo suficiente par que la condicion de piloto se repita una y otra vez con el correr de las carreras. Este eterno retorno permite al conductor, aunque sea por 13 segundos, tener su momento de gloria.",
        boost_2:
            "De esta manera, aquello que parece ser una linea recta con dos autos se transforma en algo mucho mas complejo donde la adrenalina, la pasión y los sentidos se combinan formando un ritual sagrado.",
        boost_3:
            'La pieza fue presentada como instalación site-specific en el autódromo de Avellaneda en el 2018 y tambien en "La Noche de los Museos" en 2019.',
        boost_4:
            "Diseñado y realizado por Juan Ignacio Migliardo, Abril Portillo, Harry Piluso Mulhall, Octavio Castiñeira y Pedro Falco.",
        meta_0:
            "Más allá de lo que se da. Data about data. An audio spectrum visualization.",
        sr_sale:
            "Imagen generada digitalmente y procesada en tiempo real. La obra fue tokenizada en la red Ethereum con contratos SuperRare y actualmente se encuentra a la venta.",
        sr_sold:
            "Imagen generada digitalmente y procesada en tiempo real. La obra fue tokenizada en la red Ethereum con contratos SuperRare y actualmente se encuentra vendida.",
        aurora_0:
            "Espalda mojada. Una noche de sólido silencio jugó sus cartas y los sueños huyeron sin esperanza como la arena. Cenizas, ciego equilibrista, perdiéndose en el aire.",
        condensacion_nube_0:
            "Definidas por ellas mismas como un sistema generativo, las nubes, invitan a pensar sobre el ruido. El ruido, como una imagen, es un momento. Es todo un desafío detenerse en el ruido sin ser tomado por este. Por un lado, desde el balcón, las cosas por hacer dibujan un agujero. Por el otro, los paralelos develan la racional construcción del sistema geoide mientras las gotas, obsecuentes, acatan el camino pactado. En un primer acercamiento a la nube, emergen las consideraciones políticamente correctas: su morfología, digitada en su naturaleza, se presta al continuo cambio. A riesgo de equivocarse, no parece ser más que información que fluye camuflada en contenedores rojos, verdes y azules, un alto periodo y elevados armónicos. Sin embargo, un cambio de estado obliga a quien mira a un cambio de ánimo. Resulta obvio que aquello que se ve siempre algo genera, pero el carácter pseudo aleatorio del ruido invita a especular sobre qué genera lo que genera. Enrulado en su misma ruta cambiante de siempre, quien observa encuentra un respiro en el ruido. Sucede que el ruido no busca ser decente. El ruido tampoco precisa ningún arreglo.",
        condensacion_nube_1:
            '"Observaciones sobre el ruido en la condensación de una nube" es una serie guiada por el malestar.',
        data_sculpture_0:
            "Una escultura de datos construida a partir de twits destacados que mencionan ETH2.0. Un documento para la posteridad. Loop 1920 x 1920 px.",
        drifting_0:
            "A la deriva de un pensamiento. Agentes autónomos impulsados por valores rgb.",
        ether_0:
            "Un viaje a través del éter. La voluntad imposible de saborear lo que no pudimos vivir.",
        gray_matter_0:
            "Gray Matter es mi primera obra de arte generativa. Es un flujo continuo de datos que va a la deriva como un sistema nervioso, dejando un rastro, dibujando un camino. Más de un millón de puntos grises, nos invitan a ver pasadizos secretos que recorre el pensamiento para encontrar nuevas conexiones.",
        kinetic_sculpture_0:
            "Los datos fluyen desde su esqueleto. La construcción se revela. Coloque el cuerpo, coloque el texto. El código como ADN, explica nuestra naturaleza errática en movimiento. Vivir para siempre.",
        lockdown_0:
            "Un intento de mirarnos desde fuera como nos miramos forzadamente hacia dentro.",
        paranoia_0:
            "Un nuevo viaje retorcido a través de los misterios del pensamiento.",
        persistance_reality_0: "Un error fatal durante la simulación.",
        pixel_bloom_0: "Es para ti.-",
        promised_hesitate: "La duda llama a la puerta y el infinito se cuela dentro.",
        rhizome_0:
            '"¡Haced Rizoma y no raíz, no plantéis nunca! ¡No sembréis, horadad! ¡No seáis uno ni múltiple, sed multiplicidades! ¡Haced la línea, no el punto! La velocidad transforma el punto en línea. ¡Sed rápidos, incluso sin moveros!" - Gilles Deleuze and Félix Guattari in Capitalism and Schizophrenia (1972–1980).',
        momentum_0:
            "Cada gota de pensamiento, que no se deja pensar, sacuden mis huesos. Se escapan por mis bolsillos agujereados.",
        basura_0:
            "'Entre la basura' es un programa para ver lo que queda invisibilizado entre mi spam.",
        basura_1:
            "La aplicación funciona conectándose a la API de Google para buscar mails dentro mi carpeta de spam. Ese material es usado como prompt para generar una imagen con DALL-E. Para esto, 'Entre la basura' se conecta a la API de OpenAi y genera una imagen en tiempo real.",
        rafagas_0:
            "'Ráfagas' es una instalación interactiva que responde al movimiento de las personas. Al moverse, lxs usuarixs, ejecutan un algoritmo que devuelve el rastro de esa ráfaga. La imagen resultante, inmóvil, es la creación de interesantes follajes arrastrados por el viento.",
        biorremediaciones_0: "“¿Es posible equilibrar nuestra relación con el ecosistema? ¿Cómo podemos sanar los daños que estamos realizando a la biosfera?Estas son quizás las preguntas más urgentes de nuestro tiempo, en el que es evidente que la aceleración exponencial del modelo no sustentable en el que vivimos está llegando a un límite físico irreversible como reflejo de una profunda crisis de sentido de la sociedad capitalista”. Juan Pablo Ferlat.",
        biorremediaciones_1: "La serie Biorremediaciones es un proyecto de investigación que vincula las nuevas tecnologías de inteligencia artificial y hongos con capacidades de biorremediar degradando contaminantes del ambiente en el que el artista cultiva hongos y registra su evolución con distintas técnicas de captura fotográfica.",
        biorremediaciones_2: "Video para cuatro pantallas. Duración: 6:35”. Sin sonido. Instalado en Openhouse by Openbank, Buenos Aires (2022).",	
        biorremediaciones_3: "Desarrollo en TouchDesigner: Pedro Falco. Curaduría: Cristian Reynaga.",	
        biorremediaciones_4: "Fragmento del video.",	
        author: "diseñada por Pedro Falco @ studio.falko",
        esquejes_0: '"Esqueje" es el equivalente español de esqueje o clon. Consiste en un fragmento de tallo cortado de una planta e introducido en la tierra para que enraíce con la intención de reproducirla, generando así nuevos clones. \«Esquejes\» es un sistema generativo resultante de la jardinería algorítmica, que busca llevar al límite la singularidad de cada píxel. \Esquejes» genera formas y texturas interesantes utilizando varias capas de shaders. De este modo, la obra busca que cada píxel sea diferente de su vecino y no pierda su individualidad en el universo de las imágenes sintéticas. Porque si hay infinitos números, hay infinitos colores.',
        esquejes_1:"Durante todo el mes de Septiembre de 2023 se generaron y se exhibieron Esquejes en todas las galerías de Bright Moments (Los Angeles, Nueva York, Berlin, Londres, Ciudad de Mexico y Tokio) como también en su plataforma online. Además Esquejes fue presentado en la galeria Glitch Marfa (Marfa, Texas, Estados Unidos) durante Octubre de 2023.",
        esquejes_2: "El proyecto fue realizado en Javascript y WebGL utilizando la librería Three.js. Consiste en una profunda investigación sobre como generar imágenes con shaders. Específicamente este proyecto se centra por un lado en generar un algoritmo que genere figuras abstractas interesantes y por otra busca crear texturas con pliegues que pretendan tridimensionalidad y profundidad.",
        bioma_0:"BIOMA fue una propuesta audiovisual realizada con Agustín Cotroneo para el Laboratorio de Artes Electrónicas de Tecnópolis. Esta instalación estuvo exhibida durante los meses de julio y agosto de 2023 y consistía en 12 columnas de truss de dos lados de pantalla cada una. Cada lado de 0,50 mts x 4 mts.",
        bioma_1: "Las imagenes estuvieron diseñadas en TouchDesigner mientras que el sonido se genero a partir de los inputs de video en Ableton Live.", 
        viewer_0:"<a class='underline' target='_blank' href='https://baked-model-viewer.netlify.app/'>baked-model-viewer</a>↗ permite explorar modelos 3D con texturas bakeadas en formato GLB. Podes subir tus propios archivos GLB que contengan texturas de color, emisivas y/o alfa, y visualizarlas en un entorno 3D web con <a class='underline' target='_blank' href='https://threejs.org/docs/#examples/en/controls/PointerLockControls'>point-locker-controls</a>↗.",
        viewer_1:"La aplicación fue hecha usando Three.js, Svelte y Tailwind. Funciona incluyendo las palabras \"color\", \"emissive\", y/o \"alpha\" en los nombres de los archivos de texturas de tus imágenes.",
        tkd_0:"Tae Kwon Do Evolution es una aplicación web para aprender y practicar taekwondo online. La aplicación contiene información sobre distintas formas del taekwondo acompañado por un modelo 3D interactivo que muestra los movimientos.",
        tkd_1:"La aplicación fue hecha usando Three.js, Svelte y Tailwind.",
        srchers_0:"Realicé la landing page de SRCHERS la cual consiste en un terreno procedural hecho en Three.js y una camara interactiva que responde a las coordenadas del mouse.",
        artdao_0:"Desarrollé la web de ArtDAO, un proyecto innovador que incorpora tres estilos distintivos. La página integra Three.js con Svelte para ofrecer una experiencia interactiva y envolvente. Además, cuenta con diversas secciones que capturan y reflejan fielmente el ethos y la esencia del proyecto ArtDAO.",
        cookies:
            "Página diseñada contemplando tu privacidad, sin cookies, publicidad o pedido de ningun tipo. Sólo cachea las imágenes. La web está hosteada @ netlify.com y open source @ github.com/pedrofalco",
    },
  };